---
- name: Firewall - Allow Splunk Indexer Cluster ports
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
    immediate: true
  loop: "{{ splunk_indexer_cluster_ports }}"
  notify:
    - Reload firewalld