---
- name: Firewall - Allow Splunk common service ports
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
    immediate: true
  loop: "{{ splunk_common_firewall_ports }}"
  notify:
    - Reload firewalld