---
- name: Firewall - Allow Splunk Search Head Cluster ports
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
    immediate: true
  loop: "{{ splunk_search_head_cluster_ports }}"
  notify:
    - Reload firewalld