- name: Splunk - Copy installation package to target server
  ansible.builtin.copy:
    src: files/{{ splunk_package }}
    dest: /tmp/{{ splunk_package }}
    owner: "{{ splunk_user }}"
    group: "{{ splunk_group }}"
    mode: "0644"