- name: Universal Forwarder - Copy installation package to target server
  ansible.builtin.copy:
    src: "{{ splunk_uf_package }}"
    dest: "/tmp/{{ splunk_uf_package }}"
    owner: "{{ splunk_uf_user }}"
    group: "{{ splunk_uf_group }}"
    mode: "0644"