---
- name: Universal Forwarder - Install OS required system packages for Splunk
  ansible.builtin.include_role:
    name: splunk_common
    tasks_from: packages.yml
- name: Universal Forwarder - Configure OS system hostname
  ansible.builtin.include_role:
    name: splunk_common
    tasks_from: configure_hostname.yml
- import_tasks: download_package.yml
- import_tasks: extract_package.yml
- import_tasks: create_user.yml
- import_tasks: initialize_splunk_forwarder.yml
- import_tasks: enable-boot-start.yml
- import_tasks: configure_deployment_client.yml
